version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=academic_performance'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=root'
    ports:
      - "5432:5432"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: academic-performance
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/academic_performance
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_FLYWAY_PASSWORD=root
    depends_on:
      - postgres
    ports:
      - '8090:8090'