spring:
  application:
    name: academic-performance-service
  datasource:
    username: root
    password: root
    url: jdbc:postgresql://localhost:5440/academic_performance
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8090
  servlet:
    context-path: /academic-performance/api/v1

logging:
  level:
    org:
      hibernate:
        SQL: debug